version: "3"
services:

  php:
    restart: always
    container_name: "php"
    build: ./php
    tty: true
    environment:
      - EXMENT_URL=192.168.11.52
    networks:
      base_network:
        ipv4_address: 192.168.13.13
    working_dir: /root/workspace
    volumes:
      - ./php/driver/:/root/workspace
      - ./web-server-load-tester:/root/workspace/web-server-load-tester

networks:
  base_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.13.0/24
